allo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('interior/', include('interior.urls')),
    path('recipe/', include('recipe.urls')),
    path('recycle/', include('recycle.urls')),
    path('', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recycle/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "recycle_user"

urlpatterns = [
    path('', views.recycle_main, name='recycle_main'),
    path('category/<str:category_name>/', views.CategoryDetail.as_view(), name='category_detail'),
    path('<str:category_name>/<str:item_name>/', views.RecycleDetail.as_view(), name='recycle_detail'),
    path('<str:category_name>/<str:item_name>/edit/', views.RecycleUpdate.as_view(), name='recycle_update'),
    path('<str:category_name>/<str:item_name>/delete/', views.RecycleDelete.as_view(), name='recycle_delete'),
    path('trash/', views.trash, name='trash'),
    path('can/', views.can, name='can'),
    path('paper/', views.paper, name='paper'),
    path('plastic/', views.plastic, name='plastic'),
    path('food/', views.food, name='food'),
    path('vinyl/', views.vinyl, name='vinyl'),
    path('clothing/', views.clothing, name='clothing'),
    path('map/', views.map, name='map'),
    path('create/', views.RecycleCreate.as_view(), name='recycle_create'),
    path('category', views.CategoryDetail.as_view(), name='recycle_category'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recycle/models.py
from django.db import models
from django.conf import settings

class Recycle(models.Model):
    CATEGORY_CHOICES = [
        ('trash', '일반쓰레기'),
        ('vinyl', '비닐류'),
        ('plastic', '플라스틱'),
        ('can', '병*캔류'),
        ('paper', '종이류'),
        ('food', '음식물쓰레기'),
        ('clothing', '의류수거함'),
        ('others', '기타')
    ]
   
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    name = models.CharField(max_length=100) 
    description = models.TextField() 
    image = models.ImageField(max_length=255, null=True, blank=True)
    tip = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name
    
    @property
    def image_url(self):
        return f'recycle_images/{self.image}'

recycle/forms.py
from django import forms
from .models import Recycle

class RecycleForm(forms.ModelForm):
    class Meta:
        model = Recycle
        fields = ['category', 'name', 'description', 'image', 'tip']

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance

class NewField (forms.ModelForm):
    class Meta:
        model = Recycle
        fields = ['category', 'name', 'description', 'image', 'tip']

recycle/views.py
from django.views.generic import View, DetailView, CreateView, UpdateView, DeleteView
from .models import Recycle
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseForbidden
from django.urls import reverse_lazy
from .models import Recycle
from .forms import RecycleForm
import os
from django.db.models import Q

class CategoryDetail(View):
    template_name = 'recycle/recycle_category.html'
    
    def get(self, request, category_name):
        context = {
            'category_name': category_name,
            'recycles': Recycle.objects.filter(category=category_name)
        }
        return render(request, self.template_name, context)
    

def recycle_main(request):
    search_performed = False
    items = []
    if request.method == 'POST':
        query = request.POST.get('query', '')
        if query:
            search_performed = True
            items = Recycle.objects.filter(
                Q(name__icontains=query) | Q(description__icontains=query)
            )
    return render(request, 'recycle/recycle_main.html', {'items': items, 'search_performed': search_performed})

class AuthorRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseForbidden()
        return super(AuthorRequiredMixin, self).dispatch(request, *args, **kwargs)

class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff
      
class RecycleCreate(StaffRequiredMixin, CreateView):
    model = Recycle
    form_class = RecycleForm
    template_name = 'recycle/recycle_form.html'
    success_url = reverse_lazy('recycle_user:recycle_main')
#self=name(아마 쓰레기 이름ㅇ ㅇ)
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class RecycleDetail(DetailView):
    model = Recycle
    emplate_name = 'recycle/recycle_detail.html'
    
    def get_object(self):
        category_name = self.kwargs.get('category_name')
        item_name = self.kwargs.get('item_name')
        return get_object_or_404(Recycle, category=category_name, name=item_name)

class RecycleUpdate(AuthorRequiredMixin, UpdateView):
    model = Recycle
    form_class = RecycleForm
    template_name = 'recycle/recycle_form.html'

    def get_object(self):
        category_name = self.kwargs.get('category_name')
        item_name = self.kwargs.get('item_name')
        return get_object_or_404(Recycle, category=category_name, name=item_name)
    
    def get_success_url(self):
        return reverse_lazy('recycle_user:recycle_detail', kwargs={
            'category_name': self.object.category,
            'item_name': self.object.name
        })
    
class RecycleDelete(AuthorRequiredMixin, DeleteView):
    model = Recycle
    template_name = 'recycle/recycle_confirm_delete.html'
    
    def get_object(self):
        category_name = self.kwargs.get('category_name')
        item_name = self.kwargs.get('item_name')
        return get_object_or_404(Recycle, category=category_name, name=item_name)
    
    def get_success_url(self):
        return reverse_lazy('recycle_user:category_detail', kwargs={
            'category_name': self.object.category
        })
    
def trash(request):
    return render(request, 'recycle/trash.html')
    
def vinyl(request):
    return render(request, 'recycle/vinyl.html')
    
def can(request):
    return render(request, 'recycle/can.html')
    
def plastic(request):
    return render(request, 'recycle/plastic.html')

def food(request):
    return render(request, 'recycle/food.html')
    
def paper(request):
    return render(request, 'recycle/paper.html')

def clothing(request):
    return render(request, 'recycle/clothing.html')

def map(request):
    context = {
        'kakao_api_key': os.getenv('KAKAO_API_KEY'),
    }
    return render(request, 'recycle/map.html', context)

templates/recycle/can.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/recycle/recycle_category.css">
<link rel="stylesheet" href="/static/css/recycle/recycle_main.css">
<link rel="stylesheet" href="/static/css/recycle/trash.css">
{% endblock %}
{% block content %}
<div class="recycle-nav">
    <a href="{% url 'recycle_user:recycle_main' %}" id="recycle-nav-trash" class="recycle-nav-select">분리수거</a>
    <a href="{% url 'recycle_user:clothing' %}" >의류수거함</a>
</div>

<div id="recycle-sub-nav">
    <a href="{% url 'recycle_user:trash' %}">일반쓰레기</a>
    <a href="{% url 'recycle_user:vinyl' %}">비닐류</a>
    <a href="{% url 'recycle_user:plastic' %}">플라스틱</a>
    <a href="{% url 'recycle_user:can' %}">병*캔류</a>
    <a href="{% url 'recycle_user:paper' %}">종이류</a>
    <a href="{% url 'recycle_user:food'  %}">음식물쓰레기</a>
</div>
<h1 class="trash-title">병*캔류</h1>
<div class="title-underline"></div>
<div class="recycle-instructions">
    <h2>분리배출 기본 순서</h2>
    <p>1. 비운다: 내용물을 모두 비운다.</p>
    <p>2. 헹군다: 이물질을 물로 깨끗이 헹군다.</p>
    <p>3. 분리한다: 라벨, 뚜껑 등 재질이 다른 것은 분리한다.</p>
    <p>4. 섞지 않는다: 배출하려는 쓰레기를 재질과 종류 별로 구분하여 배출한다.</p>
</div>
<div class="recycle-instructions">
    <h3># 유리</h3>
    <p>내용물을 비우고 라벨 제거 후 담아 배출합니다. </p>
    <p>개인주택, 원룸 등 공동배출 장소가 없는 경우, 재활용 봉투에 담아 배출합니다.</p>
    <p>보증금 환불문구가 있는 소주·맥주병 등은 소매점 등에 반납 가능></p>

    <h3># 깨진 유리</h3>
    <p>수거작업 시 안전사고 방지를 위하여 신문지 등으로 감싼 후 '종량제 봉투'에 담아 일반쓰레기로 배출합니다. </p>
    <p>* 깨진병, 판유리, 조명기구용 유리류는 신문지에 싸서 '종량제 봉투'로 배출</p>

    <h3># 알루미늄 캔</h3>
    <p>1. 내용물 비우고 물로 세척하기</p>
    <p>2. 라벨을 제거하고 재질이 다른 뚜껑 등은 따로 분리해 배출하기</p>
    <p>3. 압착하여 부피를 줄여 '캔류'로 분리배출하기.</p>
    <p>* 지정된 장소가 없을 경우 다른 고철과 함께 '캔류'로 분리 배출</p>
</div>
<div class="recycle-question">
  <h2>Q1. 깨진 유리는 어떻게 배출하면 되나요?</h2>
    <p>  A1. 수거작업 시 안전사고 방지를 위하여 신문지 등으로 감싼 후 '종량제 봉투'에 담아 '일반쓰레기'로 배출합니다. </p>
    <p>  깨진 유리 말고도 판유리, 조명기구용 유리 등을 신문지에 감싼 후 '종량제 봉투'에 담아 '일반쓰레기'로 배출합니다.</p>
</div>
<div class="recycle-guide">
    <p>✔︎ 재활용품은 투명 비닐에 담아 배출하시기 바랍니다.</p>
    <p>✔︎ 내집 또는 내상가 건물앞에 배출하며, 아파트 등 공동주택은 공동배출 장소에 배출하시기 바랍니다. </p>
</div>
<div class="btn-container">
    <a href="{% url 'recycle_user:recycle_main' %}" class="trash-main-btn">메인으로 돌아가기</a>
</div>
{% endblock %}
{% block script %}
    <script src="/static/js/recycle/recycle_category.js"></script>
{% endblock %}

templates/recycle/clothing.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/recycle/recycle_category.css">
<link rel="stylesheet" href="/static/css/recycle/recycle_main.css">
<link rel="stylesheet" href="/static/css/recycle/clothing.css">
{% endblock %}
{% block content %}
<div class="recycle-nav">
    <a href="{% url 'recycle_user:recycle_main' %}" id="recycle-nav-trash">분리수거</a>
    <a href="{% url 'recycle_user:clothing' %}" class="recycle-nav-select">의류수거함</a>
</div>

<div id="recycle-sub-nav">
    <a href="{% url 'recycle_user:trash' %}">일반쓰레기</a>
    <a href="{% url 'recycle_user:vinyl' %}">비닐류</a>
    <a href="{% url 'recycle_user:plastic' %}">플라스틱</a>
    <a href="{% url 'recycle_user:can' %}">병*캔류</a>
    <a href="{% url 'recycle_user:paper' %}">종이류</a>
    <a href="{% url 'recycle_user:food'  %}">음식물쓰레기</a>
</div>
<a href="{% url 'recycle_user:map' %}" class="map-btn">
    <img src="/static/img/polygon.svg" alt="">
    <p>내 주변 의류수거함 찾기</p>
</a>
<h1 class="clothing-title">의류수거함 이용방법</h1>
<div class="title-underline"></div>
<div class="recycle-instructions clothing-instructions">
    <h2># 의류 수거함은 언제 사용하나요?</h2>
    <p>깨끗하고 다른 사람이 재사용할 수 있는 옷이나 신발, 가방 등은 “의류수거함”에 버려주세요.</p>
    <h2># 그럼 더러운 옷은 어디에 분리배출 하나요?</h2>
    <p>찢어지거나 오염이 심해 다른 사람이 재사용하지 못 하는 상태라면 '종량제 봉투'에 담아 '일반쓰레기'로 버려주세요.</p>
</div>
<div class="btn-container">
    <a href="{% url 'recycle_user:recycle_main' %}" class="trash-main-btn">메인으로 돌아가기</a>
</div>
{% endblock %}
{% block script %}
<script src="/static/js/recycle/recycle_category.js"></script>
{% endblock %}

templates/recycle/food.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/recycle/recycle_category.css">
<link rel="stylesheet" href="/static/css/recycle/recycle_main.css">
<link rel="stylesheet" href="/static/css/recycle/trash.css">
{% endblock %}
{% block content %}
<div class="recycle-nav">
    <a href="{% url 'recycle_user:recycle_main' %}" id="recycle-nav-trash" class="recycle-nav-select">분리수거</a>
    <a href="{% url 'recycle_user:clothing' %}">의류수거함</a>
</div>

<div id="recycle-sub-nav">
    <a href="{% url 'recycle_user:trash' %}">일반쓰레기</a>
    <a href="{% url 'recycle_user:vinyl' %}">비닐류</a>
    <a href="{% url 'recycle_user:plastic' %}">플라스틱</a>
    <a href="{% url 'recycle_user:can' %}">병*캔류</a>
    <a href="{% url 'recycle_user:paper' %}">종이류</a>
    <a href="{% url 'recycle_user:food'  %}">음식물쓰레기</a>
</div>

<h1 class="trash-title">음식물 쓰레기</h1>
<div class="title-underline"></div>
<div class="recycle-instructions">
    <h2>분리배출 기본 순서</h2>
    <p>1. 비운다: 내용물을 모두 비운다.</p>
    <p>2. 헹군다: 이물질을 물로 깨끗이 헹군다.</p>
    <p>3. 분리한다: 라벨, 뚜껑 등 재질이 다른 것은 분리한다.</p>
    <p>4. 섞지 않는다: 배출하려는 쓰레기를 재질과 종류 별로 구분하여 배출한다.</p>
</div>
<div class="recycle-instructions">
    <h2>배출장소에 따라 구분되는 음식물 처리 방법!</h2>
    <h3># 개인주택, 원룸 등</h3>
    <p>음식물의 수분을 최대한 제거한 후 음식물쓰레기 봉투에 담아 정해진 장소, 정해진 시간에 둬야 합니다. </p>
    <p>이때 봉투 안에 다른 이물질(봉투, 꼬치 등)이 포함되지는 않았는지 확인한 후 배출합니다.</p>

    <h3># 아파트 등 공동주택</h3>
    <p>정해진 통에 음식물을 부어 배출하도록 되어있는 곳도 있고, 개인이 음식물 쓰레기 봉투에 담아 버리도록 되어있는 곳도 있습니다.</p>
    <p>음식물의 수분을 최대한 제거한 후 음식물쓰레기 봉투, 혹은 음식물 전용 쓰레기통에 배출합니다.</p>
</div>
<div class="recycle-question">
    <h2>Q1. 채소나 과일 씨도 음식물쓰레기로 분류되나요?</h2>
    <p>A1. 아니요, 일반쓰레기로 분류됩니다. </p>
    <p>그밖에도 고추씨, 어패류의 껍데기나 뼈, 알껍질, 육류의 뼈, 각종 차류(녹차 등) 찌꺼기, 한약재 찌꺼기, 복어내장 등은 음식물 쓰레기가 아닙니다. 음식물과 분리하여 '종량제 봉투'에 담아 '일반쓰레기'로 배출해 주세요!</p>
    <h2>Q2. 못먹게 된 김치는 음식물 쓰레기에 버리면 될까요?</h2>
    <p>A2. 김치와 같이 소금기가 있는 음식(된장, 고추장 등)은 물에 헹궈 소금기를 덜어내어 '음식물쓰레기'로 배출하거나,</p>
    <p>그렇지 않다면 '종량제 봉투'에 담아 '일반쓰레기'로 배출합니다.</p>
</div>
<div class="recycle-guide">
    <p>✔︎ 음식물쓰레기는 가축 사료로 사용되기 때문에 일반쓰레기와 분리 배출하는 것이 중요합니다.</p>
    <p>✔︎ 내집 또는 내상가 건물 앞에 배출하며, 아파트 등 공동주택은 공동배출 장소에 배출하시기 바랍니다.</p>
</div>
<div class="btn-container">
    <a href="{% url 'recycle_user:recycle_main' %}" class="trash-main-btn">메인으로 돌아가기</a>
</div>
{% endblock %}
{% block script %}
    <script src="/static/js/recycle/recycle_category.js"></script>
{% endblock %}

templates/recycle/paper.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/recycle/recycle_category.css">
<link rel="stylesheet" href="/static/css/recycle/recycle_main.css">
<link rel="stylesheet" href="/static/css/recycle/trash.css">
{% endblock %}
{% block content %}
<div class="recycle-nav">
    <a href="{% url 'recycle_user:recycle_main' %}" id="recycle-nav-trash" class="recycle-nav-select">분리수거</a>
    <a href="{% url 'recycle_user:clothing' %}">의류수거함</a>
</div>

<div id="recycle-sub-nav">
    <a href="{% url 'recycle_user:trash' %}">일반쓰레기</a>
    <a href="{% url 'recycle_user:vinyl' %}">비닐류</a>
    <a href="{% url 'recycle_user:plastic' %}">플라스틱</a>
    <a href="{% url 'recycle_user:can' %}">병*캔류</a>
    <a href="{% url 'recycle_user:paper' %}">종이류</a>
    <a href="{% url 'recycle_user:food'  %}">음식물쓰레기</a>
</div>
<h1 class="trash-title">종이류</h1>
<div class="title-underline"></div>
<div class="recycle-instructions">
    <h2>분리배출 기본 순서</h2>
    <p>1. 비운다: 내용물을 모두 비운다.</p>
    <p>2. 헹군다: 이물질을 물로 깨끗이 헹군다.</p>
    <p>3. 분리한다: 라벨, 뚜껑 등 재질이 다른 것은 분리한다.</p>
    <p>4. 섞지 않는다: 배출하려는 쓰레기를 재질과 종류 별로 구분하여 배출한다.</p>
</div>

<div class="recycle-instructions">
  <h2># 종이류 (박스, 기타 종이류)</h2>
  <p>택배 송장, 테이프 등을 제거 후 차곡차곡 접거나 끈으로 묶어 배출한다.</p>

  <h4>* 소량이거나 오염된 경우는 '일반쓰레기'로 배출</h4>
  <h4>* 오염된 종이, 영수증/전표, 코팅지, 벽지, 다른 재질이 혼합, 부착된 것은 '종량제 봉투'에 담아 '일반쓰레기'로 배출</h4>  
<h2># 종이팩</h2>
<p>1. 이물질을 물로 세척한 후 잘 말려 압착한다.</p>
<p>2. 일반 종이류와 섞이지 않도록 가급적 끈 등으로 묶어 '종이류'로 배출한다. </p>
</div>
<div class="recycle-question">
<h2>Q1. 파쇄지 같은 경우에는 어떻게 처리하나요?</h2>
<p>A1. 파쇄지는 종이류가 아닌 '종량제 봉투'에 담아 '일반쓰레기'로 배출합니다.</p>
</div>
<div class="recycle-guide">
    <p>✔︎ 재활용품은 투명 비닐에 담아 배출하시기 바랍니다.</p>
    <p>✔︎ 내집 또는 내상가 건물앞에 배출하며, 아파트 등 공동주택은 공동배출 장소에 배출하시기 바랍니다. </p>
</div>
<div class="btn-container">
    <a href="{% url 'recycle_user:recycle_main' %}" class="trash-main-btn">메인으로 돌아가기</a>
</div>

{% endblock %}
{% block script %}
    <script src="/static/js/recycle/recycle_category.js"></script>
{% endblock %}

templates/recycle/plastic.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="/static/css/recycle/recycle_category.css">
<link rel="stylesheet" href="/static/css/recycle/recycle_main.css">
<link rel="stylesheet" href="/static/css/recycle/trash.css">
{% endblock %}
{% block content %}
<div class="recycle-nav">
    <a href="{% url 'recycle_user:recycle_main' %}" id="recycle-nav-trash" class="recycle-nav-select">분리수거</a>
    <a href="{% url 'recycle_user:clothing' %}">의류수거함</a>
</div>

<div id="recycle-sub-nav">
    <a href="{% url 'recycle_user:trash' %}">일반쓰레기</a>
    <a href="{% url 'recycle_user:vinyl' %}">비닐류</a>
    <a href="{% url 'recycle_user:plastic' %}">플라스틱</a>
    <a href="{% url 'recycle_user:can' %}">병*캔류</a>
    <a href="{% url 'recycle_user:paper' %}">종이류</a>
    <a href="{% url 'recycle_user:food'  %}">음식물쓰레기</a>
</div>
<h1 class="trash-title">플라스틱 분리배출 방법</h1>
<div class="title-underline"></div>
<div class="recycle-instructions">
  <h2>분리배출 기본 순서</h2>
  <p>1. 비운다: 내용물을 모두 비운다.</p>
  <p>2. 헹군다: 이물질을 물로 깨끗이 헹군다.</p>
  <p>3. 분리한다: 라벨, 뚜껑 등 재질이 다른 것은 분리한다.</p>
  <p>4. 섞지 않는다: 배출하려는 쓰레기를 재질과 종류 별로 구분하여 배출한다.</p>
</div>
<div class="recycle-instructions">
    <h2>플라스틱은 투명 페트병과 그 외로 구분하여 배출합니다.</h2>
    <h3># 투명 페트병(생수, 콜라, 사이다 등)</h3>
    <p>1. 내용물을 비우고 물로 세척한다.</p>
    <p>2. 재질이 다른 라벨 등을 모두 제거하여 '비닐류'로 배출한다.</p>
    <p>3. 최대한 압축하여 뚜껑을 닫는다.</p>
    <p>4. 전용 수거함에 배출하거나 따로 모아 '페트'로 배출한다.</p>

    <h3># 유색 페트병(맥주 등)</h3>

    <p>1. 내용물을 비우고 물로 세척한다.</p>
    <p>2. 재질이 다른 라벨 등을 모두 제거하여 '비닐류'로 배출한다.</p>
    <p>3. 최대한 압축한다.(뚜껑은 닫고 함께 버려도, 따로 분리하여 버려도 무방)</p>
    <p>4. 다른 일반 플라스틱과 함께 '플라스틱'으로 배출한다.</p>

    <h3># 그 외 플라스틱</h3>
    <p>1. 내용물을 비우고 물로 세척한다.</p>
    <p>2. 재질이 다른 라벨, 부속품 등을 모두 제거하여 '플라스틱'으로 배출한다.</p>
    <li>용기의 펌프(금속 스프링), 칫솔, 볼펜 등 다른 재질이 혼합, 부착된 것은 '종량제 봉투'에 담아 '일반쓰레기'로 배출한다.</li>
</div>
<div class="recycle-question">
    <h2>Q1. 은색 보냉팩은 일반쓰레기인가요?</h2>
    <p>    A1. 네. 은색 보냉팩은 여러 물질이 혼합되어 있어 재활용이 불가능합니다. '종량제 봉투'에 담아 '일반쓰레기'로 배출해 주세요.</p>
</div>
<div class="recycle-guide">
    <p>✔︎ 재활용품은 투명 비닐에 담아 배출하시기 바랍니다.</p>
    <p>✔︎ 내집 또는 내상가 건물앞에 배출하며, 아파트 등 공동주택은 공동배출 장소에 배출하시기 바랍니다. </p>
</div>
<div class="btn-container">
    <a href="{% url 'recycle_user:recycle_main' %}" class="trash-main-btn">메인으로 돌아가기</a>
</div>
{% endblock %}
{% block script %}
    <script src="/static/js/recycle/recycle_category.js"></script>
{% endblock %}

templates/recycle/recycle_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>글 삭제 확인</h1>
<p>정말로 "{{ object.name }}" 항목을 삭제하시겠습니까?</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit">삭제</button>
</form>

<a href="{% url 'recycle_user:recycle_detail' category_name=recycle.category item_name=recycle.name %}">취소</a>
{% endblock %}

templates/recycle/recycle_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="/static/css/recycle/recycle_category.css">
<link rel="stylesheet" href="/static/css/recycle/recycle_main.css">
<link rel="stylesheet" href="/static/css/recycle/recycle_detail.css">
{% endblock %}
{% block content %}
<div class="recycle-nav">
    <a href="{% url 'recycle_user:recycle_main' %}" id="recycle-nav-trash" class="recycle-nav-select">분리수거</a>
    <a href="{% url 'recycle_user:clothing' %}">의류수거함</a>
</div>

<div id="recycle-sub-nav">
    <a href="{% url 'recycle_user:trash' %}">일반쓰레기</a>
    <a href="{% url 'recycle_user:vinyl' %}">비닐류</a>
    <a href="{% url 'recycle_user:plastic' %}">플라스틱</a>
    <a href="{% url 'recycle_user:can' %}">병*캔류</a>
    <a href="{% url 'recycle_user:paper' %}">종이류</a>
    <a href="{% url 'recycle_user:food'  %}">음식물쓰레기</a>
</div>
<div class="recycle-detail-container">
    {% if recycle.image %}
    <img src="{{ recycle.image.url }}" alt="{{ recycle.name }}">
    {% endif %}
    <div>
        <div>
            <p class="recycle-category">{{ recycle.get_category_display }}</p>
            <h1>{{ recycle.name }}</h1>            
        </div>
        <p class="recycle-desc">{{ recycle.description }}</p>
        {% if recycle.tip %}
        <p class="recycle-tip">{{ recycle.tip }}</p>
        {% endif%}
    </div>    
</div>

{% if user.is_staff %}
<div class="recycle-detail-btns">
    <a href="{% url 'recycle_user:recycle_update' category_name=recycle.category item_name=recycle.name %}">수정</a>
    <a href="{% url 'recycle_user:recycle_delete' category_name=recycle.category item_name=recycle.name %}">삭제</a>
{% endif %}
</div>
{% endblock %}
{% block script %}
    <script src="/static/js/recycle/recycle_category.js"></script>
{% endblock %}