allo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('interior/', include('interior.urls')),
    path('recipe/', include('recipe.urls')),
    path('recycle/', include('recycle.urls')),
    path('', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/urls.py
from django.urls import path
from . import views

app_name = 'community_user'

urlpatterns = [
    path('events/', views.event_list, name='event_list'),
    path('events/create/', views.event_create, name='event_create'),
    path('events/<int:pk>/', views.event_detail, name='event_detail'),
    path('notices/', views.notice_list, name='notice_list'),
    path('notices/<int:pk>/', views.notice_detail, name='notice_detail'),
    path('notices/create/', views.notice_create, name='notice_create'),
    path('notices/<int:pk>/delete/', views.notice_delete, name='notice_delete'),
    path('events/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('chatrooms/', views.chatroom_list, name='chatroom_list'),
    path('chatroom/<int:pk>/<str:username>/', views.chatroom_detail, name='chatroom_detail'),
    path('start_chat/<str:username>/', views.start_chat, name='start_chat'),
    path('send_friend_request/<str:username>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('decline_friend_request/<int:request_id>/', views.decline_friend_request, name='decline_friend_request'),
    path('post/', views.post_list, name='post_list'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/update/<int:pk>/', views.post_update, name='post_update'),
    path('post/delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('post/<int:pk>/bookmark/', views.bookmark_post, name='bookmark_post'),
    path('post/bookmarked/', views.bookmarked_posts, name='bookmarked_posts'),
    path('<int:pk>/', views.comments_create, name='comments_create'),
    path('post/<int:post_id>/comments/<int:comment_id>/delete/', views.comments_delete, name='comments_delete'),
    path('rule/', views.rule_view, name='rule'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users_user"

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('mypage/', views.mypage_view, name='mypage'),
    path('profile/edit/', views.profile_edit_view, name='profile_edit'),
    path('friend/<str:username>/', views.friend_list, name='friend_list'),
    path('friend/profile/<str:username>/', views.friend_profile_view, name='friend_profile'),
    path('friend/delete/<str:username>/', views.delete_friend, name='delete_friend'), 
    # path('change_pw/', views.change_pw, name='change_pw'),
    path('search/', views.search, name='search'),
    path('notifications/', views.notification, name='notification'),  # 알람 리스트
    path('notifications/read/', views.mark_notifications_as_read, name='mark_notifications_as_read'),  # 알람 읽음 처리
    path('notifications/delete/', views.delete_notification, name='delete_notification'),
    
]

community/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    image = models.ImageField(upload_to='event_images/', verbose_name="이벤트 포스터", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

class Notice(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='notice_images/', verbose_name="공지 이미지", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class ChatRoom(models.Model):
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='chatrooms')
    name = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Message(models.Model):
    chatroom = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='messages/', null=True, blank=True)

    def __str__(self):
        return f'{self.sender.username}: {self.content}'
    


class CommunityPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', verbose_name="이미지", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    date_posted = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_likes', blank=True)
    bookmarks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_bookmarks', blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def total_bookmarks(self):
        return self.bookmarks.count()

class FriendRequest(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_requests_community', on_delete=models.CASCADE)
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_requests_community', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.from_user} -> {self.to_user}"

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='community_comments')
    post = models.ForeignKey(CommunityPost, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content




# class Notification(models.Model):
#     NOTIFICATION_TYPES = (
#         ('like', 'Like'),
#         ('comment', 'Comment'),
#         ('message', 'Message'),
#     )

#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
#     sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_notifications')
#     notification_type = models.CharField(max_length=20, choices=NOTIFICATION_TYPES)
#     post = models.ForeignKey(CommunityPost, on_delete=models.CASCADE, null=True, blank=True)
#     message = models.ForeignKey(Message, on_delete=models.CASCADE, null=True, blank=True)
#     timestamp = models.DateTimeField(auto_now_add=True)
#     is_read = models.BooleanField(default=False)

#     def __str__(self):
#         return f"{self.user} - {self.notification_type} - {self.timestamp}"
    

community/forms.py
from django import forms
from .models import CommunityPost, Message, Comment, Event, Notice

class PostForm(forms.ModelForm):
    class Meta:
        model = CommunityPost
        fields = ['title', 'content', 'image']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 10}),
        }

class MessageForm(forms.ModelForm):
    content = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '메시지를 입력하세요...'}),
    )

    class Meta:
        model = Message
        fields = ['content', 'image']

    def clean(self):
        cleaned_data = super().clean()
        content = cleaned_data.get('content')
        image = cleaned_data.get('image')

        if not content and not image:
            raise forms.ValidationError("내용이나 이미지를 입력해야 합니다.")

        return cleaned_data

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class EventForm(forms.ModelForm):
    start_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    end_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = Event
        fields = ['title', 'start_date', 'end_date', 'description','image']


class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', 'content', 'image']

templates/community/bookmarked_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmarked Posts</title>
</head>
<body>
    <div>
        <h1>Bookmarked Posts</h1>
        {% if posts %}
            {% for post in posts %}
                <div>
                    <div>
                        <h2>{{ post.title }}</h2>
                        <p>{{ post.content }}</p>
                        <a href="{% url 'community_user:post_detail' post.id %}">View Post</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No posts have been bookmarked yet.</p>
        {% endif %}
        <a href="{% url 'users_user:home' %}">Back to Home</a>
    </div>
</body>
</html>

templates/community/event_detail.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/community/event_detail.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category community-category-selected"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<div class="event-detail-container">
    <div class="event-detail-top">
        <h2 class="event-title">{{ event.title }}</h2>
        <div>
            {% if user.is_staff %}
                <a href="{% url 'community_user:event_delete' event.pk %}" class="btn btn-danger" onclick="return confirm('이벤트를 정말로 삭제하시겠습니까?');">삭제</a>
            {% endif %}
        </div>        
    </div>
    {% if event.image %}
    <img src="{{ event.image.url }}" alt="{{ event.title }}" class="event-img">
    {% endif %}
    <p class="event-desc">{{ event.description|linebreaksbr }}</p>
    <div class="event-date-container">
        <h3>
            시작
        </h3>
        <p>
            {{ event.start_date }}
        </p>
    </div>
    <div class="event-date-container">
        <h3>
            끝
        </h3>
        <p>
            {{ event.end_date }}
        </p>        
    </div>
    <div class="event-btn-container">
        <a href="{% url 'community_user:event_list' %}" class="event-detail-btn">목록</a>
    </div>
</div>
    {% endblock %}

templates/community/event_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="/static/css/community/community_list.css">
    <link rel="stylesheet" href="/static/css/community/event_form.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category community-categoty-selected"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<h1 class="event-form-title">이벤트 작성</h1>
<form method="post" enctype="multipart/form-data" class="event-from-container">
    {% csrf_token %}
    <div>
        <label for="id_title">제목</label>
        {{ form.title }}
    </div>
    <div>
        <label for="id_description">내용</label>
        {{ form.description }}
    </div>
    <div>
        <label for="id_start_date">시작 날짜</label>
        {{ form.start_date }}
    </div>
    <div>
        <label for="id_end_date">마감 날짜</label>
        {{ form.end_date }}
    </div>
    <div>
        <label for="id_image">이미지</label>
        {{ form.image }}
    </div>
    <div class="event-btn">
        <button type="submit">이벤트 작성</button>
    </div>
</form>
{% endblock %}

templates/community/event_list.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/community/event_list.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category community-category-selected"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<div class="community-content">
    {% if user.is_staff %}
    <div class="event-btn">
        <a href="{% url 'community_user:event_create' %}">이벤트 작성</a>
    </div>
    {% endif %}
    <div class="event-post-container">
        {% for event in events %}
        <a href="{% url 'community_user:event_detail' event.pk %}" class="event-post">
            {% if event.image %}
                <img src="{{ event.image.url }}" alt="{{ event.title }}" class="event-img">
            {% else %}
                <img src="/static/img/empty3.svg" alt="" class="event-icon">
            {% endif %}
            <h2>{{ event.title }}</h2>
            <h4>{{ event.start_date }} </br>~ {{ event.end_date }}</h4>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/community/notice_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="/static/css/community/event_detail.css">
<link rel="stylesheet" href="/static/css/community/notice_detail.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category community-category-selected"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<div class="notice-detail-container">
    <div>
        <h1>{{ notice.title }}</h1>
        <div>
            {% if user.is_staff %}
                <a href="{% url 'community_user:notice_delete' notice.pk %}" class="notice-delete" onclick="return confirm('공지를 정말로 삭제하시겠습니까?');">삭제</a>
            {% endif %}
        </div>   
    </div>
    <p>{{ notice.created_at }}</p>
    {% if notice.image %}
    <img src="{{ notice.image.url }}" alt="{{ notice.title }}">
    {% endif %}
    <p class="notice-detail-content">{{ notice.content|linebreaksbr }}</p>
    <a href="{% url 'community_user:notice_list' %}" class="event-detail-btn">목록</a>    
</div>


{% endblock %}

templates/community/notice_form.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/community/event_list.css">
<link rel="stylesheet" href="/static/css/community/notice_form.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category community-category-selected"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<h2 class="notice-form-title">공지 작성</h2>
<form method="post" enctype="multipart/form-data" class="notice-form-container">
    {% csrf_token %}
    <div>
        <div>제목</div>
        {{ form.title }}
    </div>
    <div>
        <div>내용</div>
        {{ form.content }}
    </div>
    <div>
        <div>이미지</div>
        {{ form.image }}
    </div>
    <div class="notice-form-btns">
        <a href="{% url 'community_user:notice_list' %}">목록</a>
        <button type="submit">공지 작성</button>
    </div>
</form>
{% endblock %}

templates/community/notice_list.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/community/event_list.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category community-category-selected"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<div class="community-content">
    {% if user.is_staff %}
    <div class="event-btn">
        <a href="{% url 'community_user:notice_create' %}">공지 작성</a>
    </div>
    {% endif %}
    <div class="event-post-container">
        {% for notice in notices %}
            <a href="{% url 'community_user:notice_detail' notice.pk %}" class="event-post">
                {% if notice.image %}
                    <img src="{{ notice.image.url }}" alt="{{ notice.title }}" class="event-img">
                {% else %}
                    <img src="/static/img/empty3.svg" alt="" class="event-icon">
                {% endif %}
                <h2>{{ notice.title }}</h2>
                <h3>{{ notice.created_at }}</h3>
            </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/community/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/community/community_detail.css' %}">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category community-categoty-selected"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<div class="post-detail-big-container">
    <div class="post-detail-top">
        <h1 class="post-detail-title">{{ post.title }}</h1>
        <div>
            {% if request.user == post.author %}
                <a href="{% url 'community_user:post_update' post.id %}" class="btn btn-secondary">수정</a>
                <a href="{% url 'community_user:post_delete' post.id %}" class="btn btn-danger">삭제</a>
            {% endif %}
        </div>
    </div>
    <div class="post-detail-bottom">
        <p class="post-detail-info">
            {% if post.author.profile_image %}
                <img src="{{ post.author.profile_image.url }}" alt="프로필 사진" class="mypage-img">
            {% else %}
                <img src="/static/img/user.svg" alt="기본 프로필 사진" class="mypage-img">
            {% endif %}
            {{ post.author.name }} | {{ post.date_posted|date:"Y-m-d H:i" }}
        </p>
        <div class="actions">
            <button id="like-button" data-post-id="{{ post.pk }}">
                {% if request.user in post.likes.all %}
                <img src="{% static 'img/full-heart.svg' %}" alt="좋아요 눌렀을 때 아이콘">
                {% else %}
                <img src="{% static 'img/heart.svg' %}" alt="좋아요 안 눌렀을 때 아이콘">
                {% endif %}
            </button>
            <span id="likes-count">{{ post.total_likes }}</span>
            <button id="bookmark-button" data-post-id="{{ post.pk }}" class="btn btn-info">
                {% if request.user in post.bookmarks.all %}
                    <img src="{% static 'img/full-bookmark.svg' %}" alt="북마크 눌렀을 때 아이콘">
                {% else %}
                    <img src="{% static 'img/bookmark.svg' %}" alt="북마크 안 눌렀을 때 아이콘">
                {% endif %}
            </button>
            <span id="bookmarks-count">{{ post.total_bookmarks }}</span>
            {% if request.user != post.author %}
                {% if friends %}
                    <button class="btn btn-success">친구 중</button>
                {% elif friend_request_sent %}
                    <button class="btn btn-warning">신청함</button>
                {% elif friend_request_received %}
                    <button class="btn btn-info">친구 요청 대기 중</button>
                {% else %}
                    <button id="friend-request-button" data-username="{{ post.author.username }}" class="btn btn-success">친구 추가</button>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.post_title }}" class="recipe-detail-img">
    {% endif %}
    <div class="post-detail-content-box">
        {{ post.content|linebreaksbr }}
    </div>

</div>
<p class="post-detail-comment-title comment-line">{{ comments|length }}개의 댓글이 있습니다.</p>
<ul id="comment-list">
    {% for comment in comments %}
    <li class="post-detail-comment-container">
        <div class="post-detail-comment-user">
            {{ comment.user.name }}
            {% if request.user.username == comment.user.username %}
            <button class="comment-delete-button" data-comment-id="{{ comment.id }}">삭제</button>
            {% endif %}
        </div>
        <div>
            {{ comment.content }}
        </div>
    </li>
    {% endfor %}
</ul>

<!-- 댓글 작성 -->
{% if request.user.is_authenticated %}
<h3 class="post-detail-comment-title">댓글을 작성해주세요!</h3>
<form id="comment-form" method="post" action="{% url 'community_user:comments_create' post.pk %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" class="post-detail-comment-btn" value="댓글 작성">
</form>
{% endif %}

<div class="btn-div">
    <a href="{% url 'community_user:post_list' %}" class="post-detail-btn">목록</a>
</div>

<input type="hidden" id="current-username" value="{{ request.user.username }}">
<input type="hidden" id="post-id" value="{{ post.pk }}">

{% endblock %}

{% block script %}
<script src="{% static 'js/community/community_detail.js' %}"></script>
{% endblock %}

templates/community/post_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="/static/css/community/community_create.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category community-categoty-selected"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<h1 class="post-title">
    {% if form.instance.pk %}
    게시글 수정
    {% else %}
    게시글 작성
    {% endif %}
</h1>
<form method="post" enctype="multipart/form-data" class="community-create-container">
    {% csrf_token %}
    <div>
        <h2>제목</h2>
        {{ form.title }}
    </div>
    <div>
        <h2>내용</h2>
        {{ form.content }}
    </div>
    <div class="community-img-container">
        <h2>이미지</h2>
        {{ form.image }}
    </div>
    <div class="post-form-btns">
        <a href="{% url 'community_user:post_list' %}" class="community-list-btn">목록</a>
        <button type="submit" class="community-create-btn">작성하기</button>
    </div>
</form>
{% endblock %}
{% block script %}
<script src="/static/js/community/community_update.js"></script>
{% endblock %}

templates/community/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="/static/css/community/community_list.css">
{% endblock %}
{% block content %}
<div class="community-header">
    <div class="community-category community-categoty-selected"><a href="{% url 'community_user:post_list' %}">커뮤니티</a></div>
    <div class="community-category"><a href="{% url 'community_user:event_list' %}">이벤트</a></div>
    <div class="community-category"><a href="{% url 'community_user:notice_list' %}">공지</a></div>
</div>
<div class="community-top-box">
    <div id="community-top-notice">
        <a href="{% url 'community_user:rule' %}" style="text-decoration: none; color: inherit;">📣공지 및 규칙</a>
    </div>
    {% if request.user.is_authenticated %}
        <a href="{% url 'community_user:post_create' %}" id="community-top-btn">글쓰기</a>
    {% endif %}
</div>
<div class="community-post-container">
    {% if posts %}
    {% for post in posts %}
    <div class="community-post-box" data-url="{% url 'community_user:post_detail' pk=post.id %}">
        <div class="community-post-box-left">
            <div class="community-post-box-title">
                <h2>제목</h2>
                <h2 class="community-title">{{ post.title }}</h2>
            </div>
            <div class="community-post-box-author">
                <h2>작성자</h2>
                <h2>{{post.author.name}}</h2>
            </div>
            <div class="community-post-box-like">
                <img src="/static/img/full-heart.svg" alt="하트 개수" class="community-post-icon">
                <p>{{ post.total_likes }}</p>
                <img src="/static/img/full-bookmark.svg" alt="북마크 개수" class="community-post-icon">
                <p>{{ post.total_bookmarks }}</p>
            </div>
        </div>
        <div class="community-post-box-right">
            <div class="community-post-box-content">
                <h2>본문</h2>
                <p class="community-content">{{ post.content }}</p>
            </div>
            <div class="community-post-box-comment">
                <h2>댓글</h2>
                {% if post.comments.first %}
                    <p>{{ post.comments.first.content|slice:":7" }}...</p>
                {% else %}
                    <p>댓글이 없습니다.</p>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
<p class="no-post">작성된 게시글이 없습니다.</p>    
{% endif %}
</div>
{% endblock %}
{% block script %}
    <script src="/static/js/community/community_list.js"></script>
{% endblock %}