allo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('interior/', include('interior.urls')),
    path('recipe/', include('recipe.urls')),
    path('recycle/', include('recycle.urls')),
    path('', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interior/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from community import views as community_views

app_name = 'interior_user'

urlpatterns = [
    path('', views.interior_list, name='interior_list'),
    path('detail/<int:pk>/', views.interior_detail, name='interior_detail'),
    path('detail/<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('detail/<int:pk>/comments/delete/<int:id>/', views.comments_delete, name='comments_delete'),
    path('new/', views.interior_new, name='interior_new'),
    path('<int:pk>/edit/', views.interior_update, name='interior_update'),
    path('<int:pk>/delete/', views.interior_delete, name='interior_delete'),
    path('<int:pk>/like/', views.like_interior, name='like_interior'),
    path('<int:pk>/bookmark/', views.bookmark_interior, name='bookmark_interior'),
    path('bookmarked/', views.bookmarked_interiors, name='bookmarked_interiors'),
    path('send_friend_request/<str:username>/', community_views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', community_views.accept_friend_request, name='accept_friend_request'),
    path('decline_friend_request/<int:request_id>/', community_views.decline_friend_request, name='decline_friend_request'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipe/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import recipe_create_view, RecipeListView,recipe_detail_view, recipe_edit_view, recipe_delete_view, bookmarked_recipes, bookmark_recipe, like_recipe, liked_recipes, comments_delete, comments_create
from django.conf import settings
from django.conf.urls.static import static
from community import views as community_views
from . import views

app_name = 'recipe_user'

urlpatterns = [
    path('recipe_create/', login_required(recipe_create_view), name='recipe_create'),
    path('recipe_list/', RecipeListView.as_view(), name='recipe_list'),
    path('<int:id>/', recipe_detail_view ,name='recipe_detail'),
    path('<int:id>/edit/', login_required(recipe_edit_view), name='recipe_edit'),
    path('<int:id>/delete/', login_required(recipe_delete_view), name='recipe_delete'),
    path('<int:id>/like/', like_recipe, name='like_recipe'),
    path('liked/', liked_recipes, name='liked_recipes'),
    path('<int:id>/bookmark/', bookmark_recipe, name='bookmark_recipe'),
    path('bookmarked/', bookmarked_recipes, name='bookmarked_recipes'),
    path('<int:id>/comments/', comments_create, name='comments_create'),
    path('<int:recipe_id>/comments/<int:comment_id>/delete/', comments_delete, name='comments_delete'),
    path('<int:id>/recommend/', views.recommend_similar_recipes, name='recommend_similar_recipes'),
    path('send_friend_request/<str:username>/', community_views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', community_views.accept_friend_request, name='accept_friend_request'),
    path('decline_friend_request/<int:request_id>/', community_views.decline_friend_request, name='decline_friend_request'),
    path('recipe/<int:id>/like/', views.recommend_like_recipe, name='like_recipe'),
    path('recipe/<int:id>/dislike/', views.recommend_dislike_recipe, name='dislike_recipe'),
    path('csv/like/', views.like_csv_recipe, name='like_csv_recipe'),
    path('csv/dislike/', views.dislike_csv_recipe, name='dislike_csv_recipe'),

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recycle/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "recycle_user"

urlpatterns = [
    path('', views.recycle_main, name='recycle_main'),
    path('category/<str:category_name>/', views.CategoryDetail.as_view(), name='category_detail'),
    path('<str:category_name>/<str:item_name>/', views.RecycleDetail.as_view(), name='recycle_detail'),
    path('<str:category_name>/<str:item_name>/edit/', views.RecycleUpdate.as_view(), name='recycle_update'),
    path('<str:category_name>/<str:item_name>/delete/', views.RecycleDelete.as_view(), name='recycle_delete'),
    path('trash/', views.trash, name='trash'),
    path('can/', views.can, name='can'),
    path('paper/', views.paper, name='paper'),
    path('plastic/', views.plastic, name='plastic'),
    path('food/', views.food, name='food'),
    path('vinyl/', views.vinyl, name='vinyl'),
    path('clothing/', views.clothing, name='clothing'),
    path('map/', views.map, name='map'),
    path('create/', views.RecycleCreate.as_view(), name='recycle_create'),
    path('category', views.CategoryDetail.as_view(), name='recycle_category'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users_user"

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('mypage/', views.mypage_view, name='mypage'),
    path('profile/edit/', views.profile_edit_view, name='profile_edit'),
    path('friend/<str:username>/', views.friend_list, name='friend_list'),
    path('friend/profile/<str:username>/', views.friend_profile_view, name='friend_profile'),
    path('friend/delete/<str:username>/', views.delete_friend, name='delete_friend'), 
    # path('change_pw/', views.change_pw, name='change_pw'),
    path('search/', views.search, name='search'),
    path('notifications/', views.notification, name='notification'),  # 알람 리스트
    path('notifications/read/', views.mark_notifications_as_read, name='mark_notifications_as_read'),  # 알람 읽음 처리
    path('notifications/delete/', views.delete_notification, name='delete_notification'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="icon" href="/static/img/allo_logo.jpg" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>ALLO</title>
    {% block head %} {% endblock %}
</head>
<body>
    <header id="header">
        <a href="/" id="header-logo">
            <img src="/static/img/allo_logo.jpg" alt="올로 로고 이미지" id="allo-logo-img1">
            <img src="/static/img/ALLO.svg" alt="올로 로고 이미지" id="allo-logo-img2">
        </a>
        <nav id="header-nav">
            <form method="GET" action="{% url 'users_user:search' %}" id="header-nav-search-form">
                <input type="text" name="q" id="header-nav-search" placeholder="검색어를 입력해 주세요.">
                <button type="submit" id="search_logo">
                    <img src="/static/img/search2.png" alt="검색창 아이콘" id="header-nav-search-icon">
                </button>
            </form>
            <div href="{% url 'users_user:search' %}" id="search_logo2">
                <img src="/static/img/search2.png" alt="검색창 아이콘" id="notification-icon">
            </div>
            <a href="{% url 'users_user:notification' %}" id="search_logo">
                <img src="/static/img/notification2.png" alt="알림창 아이콘" id="search-icon">
            </a>
            <div id="hamburger-btn">
                <div></div>
                <div></div>
                <div></div>
            </div>
        </nav>
        <div id="sidebar">
            <a class="sidebar-category" href="{% url 'recycle_user:recycle_main' %}">분리수거</a>
            <a class="sidebar-category" href="{% url 'interior_user:interior_list' %}">인테리어</a>
            <a class="sidebar-category" href="{% url 'recipe_user:recipe_list' %}">레시피</a>
            <a class="sidebar-category" href="{% url 'community_user:post_list' %}">커뮤니티</a>
            {% if request.user.is_authenticated %}
            <a class="sidebar-category" href="{% url 'users_user:friend_list' request.user.username %}">친구</a>
            <a class="sidebar-category" href="{% url 'users_user:mypage' %}">마이페이지</a>
            <a class="sidebar-category" href="{% url 'users_user:logout' %}">로그아웃</a>
            {% else %}
            <a class="sidebar-category" href="{% url 'users_user:signup' %}">회원가입</a>
            <a class="sidebar-category" href="{% url 'users_user:login' %}">로그인</a>
            {% endif %}
        </div>
    </header>
    <div class="main-container">
        {% block content %}

        {% endblock %}
    </div>
    <footer id="footer">
        <div>        
            <div>© ALLO. 2024 All rights reserved.</div>
            <div>
                <a href="https://github.com/TEAM-ALLO">
                    <img src="/static/img/github.svg">
                </a>
                <a href="https://instagram.com/web_allo.official">
                    <img src="/static/img/insta.svg">
                </a>
            </div>
        </div>
   
    </footer>    
</body>
<script src="/static/js/main.js"></script>
{% block script %}

{% endblock %}
</html>